---
- name: Copy the keepalived_exporter systemd service file
  template:
    src: keepalived_exporter.service.j2
    dest: /etc/systemd/system/keepalived_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart keepalived_exporter
 
- block:
    - name: Create keepalived_exporter config directory
      file:
        path: "/etc/keepalived_exporter"
        state: directory
        owner: root
        group: root
        mode: u+rwX,g+rwX,o=rX

    - name: Copy the keepalived_exporter config file
      template:
        src: config.yaml.j2
        dest: /etc/keepalived_exporter/config.yaml
        owner: root
        group: root
        mode: 0644
      notify: restart keepalived_exporter
  when:
    ( keepalived_exporter_tls_server_config | length > 0 ) or
    ( keepalived_exporter_http_server_config | length > 0 ) or
    ( keepalived_exporter_basic_auth_users | length > 0 )

- name: Create textfile collector dir
  file:
    path: "{{ keepalived_exporter_textfile_dir }}"
    state: directory
    owner: "{{ _keepalived_exporter_system_user }}"
    group: "{{ _keepalived_exporter_system_group }}"
    recurse: true
    mode: u+rwX,g+rwX,o=rX
  when: keepalived_exporter_textfile_dir | length > 0
  
