---
- name: Run role
  hosts: all
  any_errors_fatal: true
  roles:
    - ansible-memcached-exporter
  pre_tasks:
    - name: Create keepalived_exporter cert dir
      file:
        path: "{{ keepalived_exporter_tls_server_config.cert_file | dirname }}"
        state: directory
        owner: root
        group: root
    - name: Copy cert and key
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - src: "/tmp/tls.cert"
          dest: "{{ keepalived_exporter_tls_server_config.cert_file }}"
        - src: "/tmp/tls.key"
          dest: "{{ keepalived_exporter_tls_server_config.key_file }}"
  vars:
    keepalived_exporter_binary_local_dir: "/tmp/keepalived_exporter-amd64"
    keepalived_exporter_web_listen_address: "127.0.0.1:8080"
    keepalived_exporter_textfile_dir: ""
    keepalived_exporter_enabled_collectors:
      - entropy
    keepalived_exporter_disabled_collectors:
      - diskstats

    keepalived_exporter_tls_server_config:
      cert_file: /etc/keepalived_exporter/tls.cert
      key_file: /etc/keepalived_exporter/tls.key
    keepalived_exporter_http_server_config:
      http2: true
    keepalived_exporter_basic_auth_users:
      randomuser: examplepassword

