---
#- name: Prepare
#  hosts: all
#  gather_facts: false
#  tasks: []
- name: Prepare
  hosts: localhost
  gather_facts: false
  vars:
    go_arch: amd64
    keepalived_exporter_version: 0.5.0
  tasks:
    - name: Download keepalived_exporter binary to local folder
      become: false
      get_url:
        url: "https://github.com/gen2brain/keepalived_exporter/releases/download/{{ keepalived_exporter_version }}/keepalived_exporter-{{ keepalived_exporter_version }}.-{{ go_arch }}.tar.gz"
        dest: "/tmp/keepalived_exporter-{{ keepalived_exporter_version }}.-{{ go_arch }}.tar.gz"
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      run_once: true
      check_mode: false

    - name: Unpack keepalived_exporter binary
      become: false
      unarchive:
        src: "/tmp/keepalived_exporter-{{ keepalived_exporter_version }}.-{{ go_arch }}.tar.gz"
        dest: "/tmp"
        creates: "/tmp/keepalived_exporter-{{ keepalived_exporter_version }}.-{{ go_arch }}/keepalived_exporter"
      run_once: true
      check_mode: false

    - name: link to keepalived_exporter binaries directory
      become: false
      file:
        src: "/tmp/keepalived_exporter-{{ keepalived_exporter_version }}.-amd64"
        dest: "/tmp/keepalived_exporter-amd64"
        state: link
      run_once: true
      check_mode: false

    - name: install pyOpenSSL for certificate generation
      pip:
        name: "pyOpenSSL"

    - name: Create private key
      openssl_privatekey:
        path: "/tmp/tls.key"

    - name: Create CSR
      openssl_csr:
        path: "/tmp/tls.csr"
        privatekey_path: "/tmp/tls.key"

    - name: Create certificate
      openssl_certificate:
        path: "/tmp/tls.cert"
        csr_path: "/tmp/tls.csr"
        privatekey_path: "/tmp/tls.key"
        provider: selfsigned
